sonar.organization=ngokeng-rayan
sonar.projectKey=Ngokeng-Rayan_Gestion-produits-avec-pipeline
sonar.projectName=Gestion Produits Pipeline

sonar.sources=backend/app,backend/routes,frontend/src
sonar.exclusions=backend/vendor/**,backend/storage/**,frontend/node_modules/**