apiVersion: 1

contactPoints:
  - orgId: 1
    name: Email Rayan
    receivers:
      - uid: email-rayan
        type: email
        settings:
          addresses: rayanngokeng1@gmail.com
          singleEmail: false
        disableResolveMessage: false
